name: tailscale
services:
  app:
    container_name: casaOS
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - TS_HOSTNAME:casaOS
    environment:
      - TS_AUTHKEY=
    image: tailscale/tailsca
x-casaos:
  architectures:
    - arm64
    - amd64
  main: app
  description:
    en_us: 'create a local network on VPN'
  tagline:
    en_us: A tool to create a local network on VPN
  developer: Helmpupper
  author: WisdomSky
  icon: https://cdn.sanity.io/images/w77i7m8x/production/8e0455b2d9b33c6151016afdf2ea81d7623c2f04-1200x628.pngg
  thumbnail: https://cdn.sanity.io/images/w77i7m8x/production/8e0455b2d9b33c6151016afdf2ea81d7623c2f04-1200x628.png
  title:
    en_us: tailscale
  category: LinuxServer.io
  project_url:
  port_map: '8080'
